=== Xatimxta/ExtraordinariaXML/EquiposPRO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Zonaequipos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombreequipo" type="xs:string"></xs:element>
                            <xs:element name="trabajo" type="xs:string"></xs:element>
                            <xs:element name="followers" type="xs:int" maxOccurs="unbounded" minOccurs="1" ></xs:element>
                            <xs:element name="eventos_participado" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="evento" maxOccurs="unbounded" minOccurs="2"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                            <xs:element name="exitosyfracasos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="a単o" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="a単oexitos" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="exito" maxOccurs="unbounded" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="a単ofracaso" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:string" name="fracaso" maxOccurs="unbounded" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute type="xs:integer" name="numeroa単o" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="integrantes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="integrante" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3"/>
                                                                <xs:maxLength value="20"/> 
                                                            </xs:restriction> 
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="apellidos">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3"/>
                                                                <xs:maxLength value="20"/> 
                                                            </xs:restriction> 
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="cargo">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:minLength value="3"/>
                                                                <xs:maxLength value="20"/> 
                                                            </xs:restriction> 
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="fechanacimiento">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:date">
                                                                <xs:maxExclusive value="2000-01-01"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="rutaimagen">
                                                        <xs:complexType>                                                                                                  
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:anyURI">
                                                                    <xs:attribute type="xs:string" name="type"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="ultimahoraparticipar" type="xs:time"></xs:element>
                                                    <xs:element name="ultimafechaempezado" type="xs:date"></xs:element>
                                                    <xs:element name="estadisticas">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="trabajoconprogramas" type="xs:integer"></xs:element>
                                                                <xs:element name="reconocimientos" type="xs:integer"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="red_social" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="twitter"/>
                              <xs:enumeration value="facebook"/>
                              <xs:enumeration value="google"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Xatimxta/ExtraordinariaXML/Equipos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Zonaequipos SYSTEM "Equiposdtd.dtd">
<Zonaequipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EquiposPRO.xsd">    
<equipo red_social="twitter">
        <nombreequipo>YeezyMafia</nombreequipo>   
        <trabajo>Desarrollador de apps</trabajo>
        <followers>15</followers>
        <eventos_participado>
            <evento>Torneo Prax</evento>
            <evento>Torneo League</evento>
        </eventos_participado>
        <exitosyfracasos>
            <año numeroaño="1997">
                <añoexitos>
                    <exito>Evolución autocheck</exito>
                    <exito>Autofill implementado</exito>
                    <exito>Deteccion de bugs</exito>
                </añoexitos>
                <añofracaso>
                    <fracaso>Cambio de perfiles</fracaso>
                    <fracaso>Solucion online</fracaso>
                    <fracaso>Transacciones de saldo</fracaso>
                </añofracaso>
            </año>
            
            <año numeroaño="1998">
                <añoexitos>
                    <exito>Avance de cuentas</exito>
                    <exito>Limpieza hackers</exito>
                    <exito>Solucion online</exito>
                </añoexitos>
                <añofracaso>
                    <fracaso>Perdida de plantilla</fracaso>
                    <fracaso>Esacasos recursos</fracaso>
                    <fracaso>Baja bolsa</fracaso>
                </añofracaso>
            </año>
        </exitosyfracasos>
        <integrantes>
            <integrante>
                <nombre>Renzo</nombre>
                <apellidos>Gomero</apellidos>
                <cargo>Jefe</cargo>
                <fechanacimiento>1995-05-05</fechanacimiento>
                <rutaimagen type="jpg" >jpg</rutaimagen>
                <ultimahoraparticipar>05:35:00</ultimahoraparticipar>
                <ultimafechaempezado>2017-05-05</ultimafechaempezado>
                <estadisticas>
                    <trabajoconprogramas>4</trabajoconprogramas>
                    <reconocimientos>2</reconocimientos>
                </estadisticas>
            
            </integrante>
            <integrante>
                <nombre>Integrante2</nombre>
                <apellidos>Apellido2</apellidos>
                <cargo>Diseñador</cargo>
                <fechanacimiento>1995-05-05</fechanacimiento>
                <rutaimagen type="jpg" >jpg</rutaimagen>
                <ultimahoraparticipar>07:50:00</ultimahoraparticipar>
                <ultimafechaempezado>2017-05-05</ultimafechaempezado>
                <estadisticas>
                    <trabajoconprogramas>2</trabajoconprogramas>
                    <reconocimientos>1</reconocimientos>
                </estadisticas>
            
            </integrante>
            <integrante>
                <nombre>Integrante3</nombre>
                <apellidos>Apellido3</apellidos>
                <cargo>Programador</cargo>
                <fechanacimiento>1995-05-05</fechanacimiento>
                <rutaimagen type="jpg" >jpg</rutaimagen>
                <ultimahoraparticipar>07:25:00</ultimahoraparticipar>
                <ultimafechaempezado>2017-05-05</ultimafechaempezado>
                <estadisticas>
                    <trabajoconprogramas>5</trabajoconprogramas>
                    <reconocimientos>1</reconocimientos>
                </estadisticas>
            
            </integrante>
        </integrantes>
    </equipo>

    <equipo red_social="facebook">
        <nombreequipo>DesarrolladoresAppsInc</nombreequipo>  
        <trabajo>Marqueting de apps</trabajo>
        <followers>15</followers>
        <exitosyfracasos>
            <año numeroaño="1997">
                <añoexitos>
                    <exito>Presentacion congreso</exito>
                    <exito>Numero uno en ventas</exito>
                    <exito>Reconocimientos varios</exito>
                </añoexitos>
                <añofracaso>
                    <fracaso>Bajo capital</fracaso>
                    <fracaso>Sin metodos</fracaso>
                    <fracaso>Sanciones publicitarias</fracaso>
                </añofracaso>
            </año>
            
            <año numeroaño="1998">
                <añoexitos>
                    <exito>Alto rendimiento productivo</exito>
                    <exito>Alta productividad</exito>
                    <exito>Premios varios</exito>
                </añoexitos>
                <añofracaso>
                    <fracaso>Supervisar</fracaso>
                    <fracaso>Supervisar x2</fracaso>
                    <fracaso>No etiquetas</fracaso>
                </añofracaso>
            </año>
        </exitosyfracasos>
        <integrantes>
            <integrante>
                <nombre>Paolo</nombre>
                <apellidos>Porras</apellidos>
                <cargo>Jefe</cargo>
                <fechanacimiento>1995-05-05</fechanacimiento>
                <rutaimagen type="jpg" >jpg</rutaimagen>
                <ultimahoraparticipar>06:54:00</ultimahoraparticipar>
                <ultimafechaempezado>2017-05-05</ultimafechaempezado>
                <estadisticas>
                    <trabajoconprogramas>12</trabajoconprogramas>
                    <reconocimientos>5</reconocimientos>
                </estadisticas>
            
            </integrante>
            <integrante>
                <nombre>Integrante2APP</nombre>
                <apellidos>Apellido2APP</apellidos>
                <cargo>Diseño comercial</cargo>
                <fechanacimiento>1995-05-05</fechanacimiento>
                <rutaimagen type="jpg" >jpg</rutaimagen>
                <ultimahoraparticipar>06:22:00</ultimahoraparticipar>
                <ultimafechaempezado>2017-05-05</ultimafechaempezado>
                <estadisticas>
                    <trabajoconprogramas>6</trabajoconprogramas>
                    <reconocimientos>5</reconocimientos>
                </estadisticas>
            
            </integrante>
            <integrante>
                <nombre>Integrante3APP</nombre>
                <apellidos>Apellido3APP</apellidos>
                <cargo>Marqueting general</cargo>
                <fechanacimiento>1995-05-05</fechanacimiento>
                <rutaimagen type="jpg" >jpg</rutaimagen>
                <ultimahoraparticipar>08:01:00</ultimahoraparticipar>
                <ultimafechaempezado>2017-05-05</ultimafechaempezado>
                <estadisticas>
                    <trabajoconprogramas>3</trabajoconprogramas>
                    <reconocimientos>1</reconocimientos>
                </estadisticas>
            </integrante>
        </integrantes>
    </equipo>
</Zonaequipos>
